pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonnai sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Debug') {
            steps {
                echo "Current directory:"
                sh('pwd') // Check current directory
                echo "Workspace contents:"
                sh('ls -l') // List contents in the workspace
                echo "Scripts folder contents:"
                sh('ls -l ./scripts') // List the contents of the scripts folder
            }
        }
        stage('Make executable') {
            steps {
                sh('chmod +x ./scripts/fibonacci.sh')
            }
        }
        stage('Run Fibonacci Script') {
            steps {
                sh("./scripts/fibonacci.sh ${env.NUMBER}")
            }
        }
    }
}
