pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonacci sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Debug - List Files') {  // This stage will list the files in the workspace root
            steps {
                sh('pwd')  // Print the current working directory (should be the root of the workspace)
                sh('ls -la')  // List all files in the root directory of the workspace
            }
        }
        stage('Make executable') {
            steps {
                sh('chmod +x ./fibonacci.sh')  // Make the script executable
            }
        }
        stage('Run Fibonacci Script') {
            steps {
                sh("./fibonacci.sh ${env.NUMBER}")  // Run the script with the selected parameter
            }
        }
    }
}
