pipeline {
    agent any
    parameters {
        choice(name: 'NUMBER',
            choices: [10,20,30,40,50,60,70,80,90],
            description: 'Select the value for F(n) for the Fibonacci sequence.')
    }
    options {
        buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
        timeout(time: 12, unit: 'HOURS')
        timestamps()
    }
    triggers {
        cron '@midnight'
    }
    stages {
        stage('Checkout') { // Make sure the repository is being checked out
            steps {
                checkout scm
            }
        }
        stage('Debug - List Files') {  // List the files in the root workspace
            steps {
                sh('pwd')  // Print current working directory
                sh('ls -la')  // List all files in the root directory
            }
        }
        stage('Make executable') {
            steps {
                sh('chmod +x ./fibonacci.sh')  // Make the script executable
            }
        }
        stage('Run Fibonacci Script') {
            steps {
                sh("./fibonacci.sh ${env.NUMBER}")  // Run the script
            }
        }
    }
}
